### ISSUE TITLE
couldn't connect to sql database

### ISSUE THREAD

**Issue by lidulibai** [JuanZoran/Trans.nvim#13]
兄弟，报错连不上数据库怎么整
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14270445/214756601-cf8c7ebc-e12b-458d-aaad-3543710d9586.png">

**Comment by JuanZoran** [comment]
请查看～/.vim/dict 文件夹是否存在，还有里面是否安装了.db文件

**Comment by lidulibai** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14270445/214859542-b5a10cce-d4f7-4eab-81e0-649ed1b09782.png">
搞定上面那个问题之后又碰到这个

**Comment by lidulibai** [comment]
就用的readme里面那段
```lua
  use {
    'JuanZoran/Trans.nvim',
    run = 'bash ./install.sh',
    requires = 'kkharji/sqlite.lua',
    -- 如果你不需要任何配置的话, 可以直接按照下面的方式启动
    config = function ()
        require'Trans'.setup{
            -- your configuration here
        }
    end
```
neovim版本 ：NVIM v0.8.1

**Comment by lidulibai** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/14270445/214863677-a25632ea-1fae-4c61-a7b3-cf656813e3d1.png">

**Comment by JuanZoran** [comment]
问题可能是窗口标题用到了neovim-nightly的特性， 我刚刚推送了一个判断，merge到主分支了，你尝试更新看看，问题还存在吗

**Comment by lidulibai** [comment]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/14270445/214870833-a7aeccc0-68db-43a4-b7e3-ad932545d573.png">
好像变成另外一个问题了？

**Comment by lidulibai** [comment]
Translate命令，刚刚试了一下TranslateInput报之前的错误
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14270445/214876420-747e5f46-768c-43d5-9f3c-a256983763a7.png">

**Comment by JuanZoran** [comment]
我试着尝试修复了一下，你更新看看现在能否正常运行

**Comment by lidulibai** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14270445/214882657-ee311abc-a813-44cb-9a48-95ea3f41209c.png">
:Translate 命令运行的debug信息

**Comment by JuanZoran** [comment]
好了，修复了neovim的版本判断，不好意思，再更新试试吧

**Comment by lidulibai** [comment]
哪里的话，实在是十分感谢大佬的及时和回复和帮忙解决问题。
更新之后还是类似的错误
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14270445/214980576-dd5b8b6d-58fa-43ad-a26c-2aa1cf30ad4a.png">

**Comment by JuanZoran** [comment]
奇怪的是，从这个debug信息来看，好像没有什么问题， 你的系统是什么， 可能是还有其他api问题, 暂时我还无法复现
建议你更新到neovim-nightly版本: [下载地址](https://github.com/neovim/neovim/releases)

**Comment by JuanZoran** [comment]
您好，刚刚使用我安装了0.8.1的neovim版本，成功复现了该bug, 刚刚已经修复了，你现在可以更新一下，如果还遇到问题请及时反馈

**Comment by lidulibai** [comment]
可以了！大佬威武~
