### ISSUE TITLE
TranslateInput 异常

### ISSUE THREAD

**Issue by kdurant** [JuanZoran/Trans.nvim#17]
非常漂亮的插件，谢谢你

翻译输入单词有点问题
![2023-01-27_00-26](https://user-images.githubusercontent.com/2704364/214891745-58d9c0b2-dca6-4382-ad3c-2303cc1d9072.png)

以后要是可以新增viutua模式选择句子，然后直接翻译的功能就更好了

**Comment by JuanZoran** [comment]
请问您的neovim版本是0.9吗，如果不是的话我刚刚推送的更新新增加了判断，尝试更新一下，看看问题还会发生吗
>  另外TranslateInput的样式对应的是`float`样式，这个样式我还没想好怎么做，你可以看看大概的样子， 如果需要使用的话，在setup函数里指定`view.i = 'hover'`就可以把样式改成hover模式

virtual模式选择句子的功能需要用到在线查询， 目前我已经写好了 `有道， 百度，iciba, freedictionary`的接口, 但是想在float窗口中加上，但是最近没有想好float模式的布局，可能这两天会先加在`hover`模式里

如果你有float窗口布局的想法，欢迎告诉我

**Comment by JuanZoran** [comment]
刚刚更新了float的窗口size判断问题，目前`float`窗口没有将数据加入，仅仅作为一个框架展示，如果需要正常使用，可以先调成`hover`视窗，示例如下:
```lua
require('Trans').setup{
    view = {
        i = 'hover'
    },
--- 其他配置
}
````

**Comment by kdurant** [comment]
使用hover可以了，谢谢
