### ISSUE TITLE
大佬，请问这是怎么回事

### ISSUE THREAD

**Issue by quantum-mj** [JuanZoran/Trans.nvim#25]
Error executing vim.schedule lua callback: ...m/site/pack/packer/start/Trans.nvi
m/lua/Trans/window.lua:30: Invalid window id: 1003
stack traceback:
        [C]: in function 'nvim_win_set_option'
        ...m/site/pack/packer/start/Trans.nvim/lua/Trans/window.lua:30: in funct
ion 'set'
        ...m/site/pack/packer/start/Trans.nvim/lua/Trans/window.lua:82: in funct
ion 'task'
        .../pack/packer/start/Trans.nvim/lua/Trans/util/display.lua:9: in functi
on 'do_task'
        .../pack/packer/start/Trans.nvim/lua/Trans/util/display.lua:23: in funct
ion ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by JuanZoran** [comment]
请问是什么情况下出现这种情况的, 能不能给出重现的步骤

**Comment by JuanZoran** [comment]
请问是什么情况下出现这种情况的, 能不能给出重现的步骤

**Comment by JuanZoran** [comment]
已经推送了解决的版本, 尝试update一下, 如果问题还存在, 请及时反馈
