### ISSUE TITLE
ok了，谢谢大佬

### ISSUE THREAD

**Issue by quantum-mj** [JuanZoran/Trans.nvim#26]
已经推送了解决的版本, 尝试update一下, 如果问题还存在, 请及时反馈

_Originally posted by @JuanZoran in https://github.com/JuanZoran/Trans.nvim/issues/25#issuecomment-1435488937_

**Comment by JuanZoran** [comment]
没事, 可以的话,欢迎给项目点一个star, 等我开学考试完了, 会更新待办里的功能:)
