### ISSUE TITLE
希望增加 长句翻译

### ISSUE THREAD

**Issue by allinu** [JuanZoran/Trans.nvim#27]
目前只能单词翻译，希望能增加多句翻译功能。 感谢 【btw 动画精美】

**Comment by JuanZoran** [comment]
其实是加了百度在线翻译的，添加
require 'Trans'.setup{
    engine = {
       baidu ={
       appid= your id,
       appasswd= your passwd,
}
}
}
最近在重构这个插件，所以这个是实验性的，可能名字不对，具体可以看lua/Trans/query/baidu.lua

**Comment by JuanZoran** [comment]
所有的功能建议都是欢迎的，会出一个代办事项，有空就会添加功能，目前正在重构插件的结构😋

**Comment by allinu** [comment]
@JuanZoran 好的，感谢 ❤️
