### ISSUE TITLE
Translation error on the first line

### ISSUE THREAD

**Issue by JavaHello** [JuanZoran/Trans.nvim#28]
### file content
```txt
# NVIM
```
### message
```log
Error executing vim.schedule lua callback: ...kai/.local/share/nvim/lazy/Trans.nvim/lua/Trans/node.lua:8: Invalid buffer id: 21
stack traceback:
        [C]: in function 'add_hl'
        ...kai/.local/share/nvim/lazy/Trans.nvim/lua/Trans/node.lua:8: in function 'load'
        ...i/.local/share/nvim/lazy/Trans.nvim/lua/Trans/buffer.lua:114: in function 'addline'
        ...ocal/share/nvim/lazy/Trans.nvim/lua/Trans/view/hover.lua:339: in function 'frame'
        ...al/share/nvim/lazy/Trans.nvim/lua/Trans/util/display.lua:19: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by JuanZoran** [comment]
请问能否稳定重现, 请给出重现步骤, 或者最小配置

**Comment by JavaHello** [comment]
> 请问能否稳定重现, 请给出重现步骤, 或者最小配置

重现步骤
```txt
nvim
:new test.txt
i # NVIM
<ESC>
:Translate
```

**Comment by JuanZoran** [comment]
无法重现, 请尝试提供最小配置, 不过目前Main分支的版本已经遗弃, dev分支基本重写了这个插件, 要不你加我qq, 试一下dev版本的, 已经支持了有道和百度的在线翻译

**Comment by JavaHello** [comment]
> 无法重现, 请尝试提供最小配置, 不过目前Main分支的版本已经遗弃, dev分支基本重写了这个插件, 等测试没问题才会发布, 要不你加我qq, 测试一下dev版本的, 已经支持了有道和百度的在线翻译

https://github.com/JavaHello/nvim/blob/6995a787efddfd2bbfbb7c4a056baac61b950599/lua/kide/plugins/lazy-nvim.lua#L707-L732
好的，配置复制的 README 中的，等dev版本发布后我再试试

**Comment by JuanZoran** [comment]
https://github.com/folke/lazy.nvim/wiki/Minimal-%60init.lua%60-to-Reproduce-an-Issue, 建议可以学习一下最小步骤重现的方法,对以后提issue也会有帮助
