### ISSUE TITLE
是否可以添加支持 translate-shell 在线翻译

### ISSUE THREAD

**Issue by JavaHello** [JuanZoran/Trans.nvim#29]
[translate-shell](https://github.com/soimort/translate-shell)

**Comment by JuanZoran** [comment]
在线翻译的功能这个插件是做了的, 为啥还要支持这个在线翻译工具, 如果他提供了接口的话, 有没有兴趣自己封装一下, 提一个PR, 有兴趣的话我会把插件的api接口和作用都写一下

**Comment by JuanZoran** [comment]
dev分支已经基本重写了这个插件, 加入了有道和百度的在线翻译, 有兴趣尝试一下吗?
![image](https://user-images.githubusercontent.com/107862700/226174646-fa5ca68d-7e92-4795-abca-fd1590edb3f1.png)
![image](https://user-images.githubusercontent.com/107862700/226174674-af5ff9d3-6f1e-40fa-9084-8a9567c096dc.png)

**Comment by JuanZoran** [comment]
v2分支已经发布, 需要在线翻译请配置`Trans.json`
