### ISSUE TITLE
能增加一个动画开关按钮？

### ISSUE THREAD

**Issue by crusj** [JuanZoran/Trans.nvim#32]
我不想要动画，interval设置为0还是有动画效果

**Comment by JuanZoran** [comment]
设置成false即可

**Comment by crusj** [comment]
什么设置为false

**Comment by JuanZoran** [comment]
```lua
animation = {
            open = false,
            close = false,
            interval = 12,
         },
```

**Comment by crusj** [comment]
> ```lua
> animation = {
>             open = false,
>             close = false,
>             interval = 12,
>          },
> ```

报错了啊
`rror executing Lua callback: ...m/site/pack/packer/start/Trans.nvim/lua/Trans/window.lua:63: attempt to perform arithmetic on local 'target' (a nil value)                                                                           
stack traceback:
        ...m/site/pack/packer/start/Trans.nvim/lua/Trans/window.lua:63: in function 'expand'
        ...m/site/pack/packer/start/Trans.nvim/lua/Trans/window.lua:220: in function 'open_window'
        ...te/pack/packer/start/Trans.nvim/lua/Trans/view/hover.lua:364: in function <...te/pack/packer/start/Trans.nvim/lua/Trans/view/hover.lua:357>
        ...vim/site/pack/packer/start/Trans.nvim/lua/Trans/init.lua:228: in function 'translate'
        .../nvim/site/pack/packer/start/Trans.nvim/plugin/Trans.lua:5: in function <.../nvim/site/pack/packer/start/Trans.nvim/plugin/Trans.lua:5>`

**Comment by JuanZoran** [comment]
你把完整的配置发出来吧

**Comment by crusj** [comment]
> 你把完整的配置发出来吧

```
require 'Trans'.setup {
    view = {
        i = 'float',
        n = 'hover',
        v = 'hover',
    },
    hover = {
        width = 40,
        height = 27,
        border = 'rounded',
        keymap = {
            pageup = '[[',
            pagedown = ']]',
            pin = '<leader>[',
            close = '<leader>]',
            toggle_entry = '<leader>;',
            play = '_',
        },
        animation = {
            open = false,
            close = false,
            interval = 0,
        },
        auto_close_events = {
            'InsertEnter',
            'CursorMoved',
            'BufLeave',
        },
        auto_play = false,
        timeout = 3000,
        spinner = 'dots', -- 查看所有样式: /lua/Trans/util/spinner
        -- spinner = 'moon'
    },
    float = {
        width = 0.8,
        height = 0.8,
        border = 'rounded',
        keymap = {
            quit = 'q',
        },
        animation = {
            open = 'fold',
            close = 'fold',
            interval = 0,
        },
        tag = {
            wait = '#519aba',
            fail = '#e46876',
            success = '#10b981',
        },
        engine = {
            '本地',
        }
    },
    order = { -- only work on hover mode
        'title',
        'tag',
        'pos',
        'exchange',
        'translation',
        'definition',
    },
    icon = {
        star = '',
        notfound = ' ',
        yes = '',
        no = '',
        -- --- char: ■ | □ | ▇ | ▏ ▎ ▍ ▌ ▋ ▊ ▉ █
        -- --- ◖■■■■■■■◗▫◻ ▆ ▆ ▇⃞ ▉⃞
        cell = '■',
        -- star = '⭐',
        -- notfound = '❔ ',
        -- yes = '',
        -- no = ''
    },
    theme = 'default',
    -- theme = 'dracula',
    -- theme = 'tokyonight',

    db_path = '$HOME/.vim/dict/ultimate.db',

    engine = {
        -- baidu = {
        --     appid = '',
        --     appPasswd = '',
        -- },
        -- -- youdao = {
        --     appkey = '',
        --     appPasswd = '',
        -- },
    },

    -- TODO :
    -- register word
    -- history = {
    --     -- TOOD
    -- }

    -- TODO :add online translate engine
}
vim.keymap.set("n", "\\tr", '<Cmd>Translate<CR>', { desc = ' Translate' }) -- 自动判断virtual 还是 normal 模式
vim.cmd([[
hi TransWin guibg=none
hi TransPhonetic guibg=none
hi TransTranslation guifg=black
hi TransWord  guifg=black
hi TransTitle  guifg=black
hi TransTitleRound guifg=black
hi TransTag guifg=black guibg=none
hi TransExchange guifg=black guibg=none
hi TransTranslation guifg=black guibg=none
hi TransDefinition guifg=black guibg=none
hi TransWin guifg=black guibg=none
hi TransBorder guifg=#6C8ED4 guibg=none cterm=bold
hi TransFailed guifg=black guibg=none
hi TransCollins guifg=blue
]])

```

**Comment by JuanZoran** [comment]
> > 你把完整的配置发出来吧
> 
> ```
> require 'Trans'.setup {
>     view = {
>         i = 'float',
>         n = 'hover',
>         v = 'hover',
>     },
>     hover = {
>         width = 40,
>         height = 27,
>         border = 'rounded',
>         keymap = {
>             pageup = '[[',
>             pagedown = ']]',
>             pin = '<leader>[',
>             close = '<leader>]',
>             toggle_entry = '<leader>;',
>             play = '_',
>         },
>         animation = {
>             open = false,
>             close = false,
>             interval = 0,
>         },
>         auto_close_events = {
>             'InsertEnter',
>             'CursorMoved',
>             'BufLeave',
>         },
>         auto_play = false,
>         timeout = 3000,
>         spinner = 'dots', -- 查看所有样式: /lua/Trans/util/spinner
>         -- spinner = 'moon'
>     },
>     float = {
>         width = 0.8,
>         height = 0.8,
>         border = 'rounded',
>         keymap = {
>             quit = 'q',
>         },
>         animation = {
>             open = 'fold',
>             close = 'fold',
>             interval = 0,
>         },
>         tag = {
>             wait = '#519aba',
>             fail = '#e46876',
>             success = '#10b981',
>         },
>         engine = {
>             '本地',
>         }
>     },
>     order = { -- only work on hover mode
>         'title',
>         'tag',
>         'pos',
>         'exchange',
>         'translation',
>         'definition',
>     },
>     icon = {
>         star = '',
>         notfound = ' ',
>         yes = '',
>         no = '',
>         -- --- char: ■ | □ | ▇ | ▏ ▎ ▍ ▌ ▋ ▊ ▉ █
>         -- --- ◖■■■■■■■◗▫◻ ▆ ▆ ▇⃞ ▉⃞
>         cell = '■',
>         -- star = '⭐',
>         -- notfound = '❔ ',
>         -- yes = '',
>         -- no = ''
>     },
>     theme = 'default',
>     -- theme = 'dracula',
>     -- theme = 'tokyonight',
> 
>     db_path = '$HOME/.vim/dict/ultimate.db',
> 
>     engine = {
>         -- baidu = {
>         --     appid = '',
>         --     appPasswd = '',
>         -- },
>         -- -- youdao = {
>         --     appkey = '',
>         --     appPasswd = '',
>         -- },
>     },
> 
>     -- TODO :
>     -- register word
>     -- history = {
>     --     -- TOOD
>     -- }
> 
>     -- TODO :add online translate engine
> }
> vim.keymap.set("n", "\\tr", '<Cmd>Translate<CR>', { desc = ' Translate' }) -- 自动判断virtual 还是 normal 模式
> vim.cmd([[
> hi TransWin guibg=none
> hi TransPhonetic guibg=none
> hi TransTranslation guifg=black
> hi TransWord  guifg=black
> hi TransTitle  guifg=black
> hi TransTitleRound guifg=black
> hi TransTag guifg=black guibg=none
> hi TransExchange guifg=black guibg=none
> hi TransTranslation guifg=black guibg=none
> hi TransDefinition guifg=black guibg=none
> hi TransWin guifg=black guibg=none
> hi TransBorder guifg=#6C8ED4 guibg=none cterm=bold
> hi TransFailed guifg=black guibg=none
> hi TransCollins guifg=blue
> ]])
> ```

不好意思, 我刚刚测试了main分支似乎的确存在这个问题, 要不你尝试使用experimental分支, 因为main分支是上一版本的了, 我在其他分支已经重写了这个插件

**Comment by JuanZoran** [comment]
experimental分支的README有配置说明, 同时支持了百度, 有道的在线查询

**Comment by crusj** [comment]
> experimental分支的README有配置说明, 同时支持了百度, 有道的在线查询

配好了可以的，那个配置有道和百度的json我复制的demo里面的，没去填密钥，目前也是可以翻译的
另外这个为啥一定要0.9,有什么必须要依赖0.9的吗，我现在是0.8.3
![image](https://user-images.githubusercontent.com/20185895/228439843-ff6ebe8d-e18d-4622-8898-0fd42d23f890.png)
另外我发现一个问题，我在翻译划线这个位置的单词不会成功，窗口会一闪就消失了
![image](https://user-images.githubusercontent.com/20185895/228440601-43de2def-6187-4ad0-b766-26aa03414ab3.png)

**Comment by JuanZoran** [comment]
> > experimental分支的README有配置说明, 同时支持了百度, 有道的在线查询
> 
> 配好了可以的，那个配置有道和百度的json我复制的demo里面的，没去填密钥，目前也是可以翻译的 另外这个为啥一定要0.9,有什么必须要依赖0.9的吗，我现在是0.8.3 ![image](https://user-images.githubusercontent.com/20185895/228439843-ff6ebe8d-e18d-4622-8898-0fd42d23f890.png) 另外我发现一个问题，我在翻译划线这个位置的单词不会成功，窗口会一闪就消失了 ![image](https://user-images.githubusercontent.com/20185895/228440601-43de2def-6187-4ad0-b766-26aa03414ab3.png)

- 密钥只是启用在线翻译功能, 你没有填密钥可以翻译句子或者中文吗
- 需要neovim-0.9是为了启用窗口标题的功能, 建议运行一下checkhealth Trans
- 翻译frontend无法成功吗, 请告诉我你的系统版本, neovim版本, 配置, 我在我的机器上使用是可以的
![image](https://user-images.githubusercontent.com/107862700/228441546-cdca478c-f6a9-461c-b02e-12ff07757a11.png)

**Comment by crusj** [comment]
> > > experimental分支的README有配置说明, 同时支持了百度, 有道的在线查询
> > 
> > 
> > 配好了可以的，那个配置有道和百度的json我复制的demo里面的，没去填密钥，目前也是可以翻译的 另外这个为啥一定要0.9,有什么必须要依赖0.9的吗，我现在是0.8.3 ![image](https://user-images.githubusercontent.com/20185895/228439843-ff6ebe8d-e18d-4622-8898-0fd42d23f890.png) 另外我发现一个问题，我在翻译划线这个位置的单词不会成功，窗口会一闪就消失了 ![image](https://user-images.githubusercontent.com/20185895/228440601-43de2def-6187-4ad0-b766-26aa03414ab3.png)
> 
>     * 密钥只是启用在线翻译功能, 你没有填密钥可以翻译句子或者中文吗
> 
>     * 需要neovim-0.9是为了启用窗口标题的功能, 建议运行一下checkhealth Trans
> 
>     * 翻译frontend无法成功吗, 请告诉我你的系统版本, neovim版本, 配置, 我在我的机器上使用是可以的
>       ![image](https://user-images.githubusercontent.com/107862700/228441546-cdca478c-f6a9-461c-b02e-12ff07757a11.png)
说错了是下面的default

**Comment by JuanZoran** [comment]
我刚刚合并了一些小的修复, 你更新一下看看还能不能, 目前很多人还是在用main分支的代码, experimental分支的单元测试我还在写, 平时的课有点多, 所以有点慢, 单元测试还没有覆盖完全, 所以可能会有一些bug

**Comment by crusj** [comment]
> 我刚刚合并了一些小的修复, 你更新一下看看还能不能, 目前很多人还是在用main分支的代码, experimental分支的单元测试我还在写, 平时的课有点多, 所以有点慢, 单元测试还没有覆盖完全, 所以可能会有一些bug
还在上学啊，优秀！！

**Comment by JuanZoran** [comment]
一个大二的小菜鸡而已 : )

**Comment by crusj** [comment]
> 一个大二的小菜鸡而已 : )

谦虚了，希望早日正式发布，挺好用的。

**Comment by JuanZoran** [comment]
> > 一个大二的小菜鸡而已 : )
> 
> 谦虚了，希望早日正式发布，挺好用的。

目前还有一些小bug , 同时有一些想法正在考虑加上, 发布应该等我把单元测试全部写完, 我不想发布全是bug : (, 同时文档也等着我去补
