### ISSUE TITLE
最近出现问题 ，直接报错

### ISSUE THREAD

**Issue by syltharion** [JuanZoran/Trans.nvim#39]
Error executing Lua callback: ...te/pack/lazy/opt/Trans.nvim/lua/Trans/core/translate.lua:101: ...rvim/site/pack/lazy/opt/sqlite.lua/lua/sqlite/assert.lua:28: sqlite.lua: can not execute select, stardict doesn't exists.
stack traceback:
	[builtin#36]: at 0x0104b60620
	...te/pack/lazy/opt/Trans.nvim/lua/Trans/core/translate.lua:101: in function 'translate'
	.../lunarvim/site/pack/lazy/opt/Trans.nvim/plugin/Trans.lua:7: in function <.../lunarvim/site/pack/lazy/opt/Trans.nvim/plugin/Trans.lua:7>

**Comment by JuanZoran** [comment]
检查目录下词库是否存在
