### ISSUE TITLE
windows版的lazyvim找不到词库

### ISSUE THREAD

**Issue by erpingshuai** [JuanZoran/Trans.nvim#46]
我在用lazyvim windows版的,但是把词库放入指定位置,插件找不到database.

**Comment by JuanZoran** [comment]
能否提供一下checkhealth的结果呢?

**Comment by erpingshuai** [comment]
- ERROR Stardict database not found
          [Manually]: Please check the doc in github: [https://github.com/JuanZoran/Trans.nvim]
          [Automatically]: Try to run `:lua require "Trans".install()`
          
- WARNING vim.health.report_ok() is deprecated, use vim.health.ok() instead. :help |deprecated|
  This feature will be removed in Nvim version 0.11
- OK You have [neovim-nightly] 
- ERROR Backend configuration file [v:null\\Trans.json] invalid
          Please check the doc in github: [https://github.com/JuanZoran/Trans.nvim]

**Comment by JuanZoran** [comment]
你尝试配置一下dir参数, 这个参数决定了词库以及api文件的存放目录, 更改到你喜欢的目录,  然后将词库放到该目录就可以了

**Comment by erpingshuai** [comment]
好的,我试试,非常感谢

**Comment by ACupofAir** [comment]
same problem

**Comment by erpingshuai** [comment]
试了更改dir的值,好像不起作用

**Comment by ghost** [comment]
https://github.com/JuanZoran/Trans.nvim/blob/50c2f003f455ab76f3bca44f3f5e6917c65718c2/lua/Trans/init.lua#L40
在windows上，`debug.getinfo(1, 'S').source`返回的路径分隔符是`/`而不是`\`，会导致后边匹配失败。

**Comment by JuanZoran** [comment]
感谢问题反馈, 但是目前在赶土木工程作业, 可能要过两天修了 : (
