### ISSUE TITLE
lazyvim 配置设置没有反应，不能关闭auto_play选项，是我的配置写错了吗？请帮我看一下

### ISSUE THREAD

**Issue by xinmodao** [JuanZoran/Trans.nvim#51]
return {
  {
    "JuanZoran/Trans.nvim",
    build = function()
      require("Trans").install()
    end,
    keys = {
      -- 可以换成其他你想映射的键
      { "mm", mode = { "n", "x" }, "<Cmd>Translate<CR>", desc = " Translate" },
      { "mk", mode = { "n", "x" }, "<Cmd>TransPlay<CR>", desc = " Auto Play" },
      -- 目前这个功能的视窗还没有做好，可以在配置里将view.i改成hover
      { "mi", "<Cmd>TranslateInput<CR>", desc = " Translate From Input" },
    },
    dependencies = { "kkharji/sqlite.lua" },
    opts = {
      -- your configuration there
      theme = "tokyonight",
      frontend = {
         default = {auto_play = false},
      },
    },
  },
}

**Comment by ZouDongj** [comment]
解决了吗，我的配置也不生效

**Comment by ZouDongj** [comment]
config = function(_, opts)
      require("Trans").setup(opts)
    end,

**Comment by ZouDongj** [comment]
`config = function(_, opts)
      require("Trans").setup(opts)
    end,
`

**Comment by xinmodao** [comment]
thank you!! :)
