### ISSUE TITLE
找不到stardict 

### ISSUE THREAD

**Issue by lyy4758** [JuanZoran/Trans.nvim#52]
![image](https://github.com/JuanZoran/Trans.nvim/assets/29500263/db94cddf-d8eb-4764-90b2-626dc55df88c)
这是我的 lazy trans的配置	{
		"JuanZoran/Trans.nvim",
		build = function()
			require("Trans").install()
		end,
		keys = {
			{ "tm", mode = { "n", "x" }, "<Cmd>Translate<CR>", desc = " Translate" },
			-- 目前这个功能的视窗还没有做好，可以在配置里将view.i改成hover
			{ "ti", "<Cmd>TranslateInput<CR>", desc = " Translate From Input" },
		},
		dependencies = { "kkharji/sqlite.lua" },
		-- opts = {
		-- 	-- your configuration there
		-- 	theme = "tokyonight",
		-- 	frontend = {
		-- 		default = { auto_play = false },
		-- 	},
		-- },
		config = function(_)
			require("Trans").setup()
		end,
	},
这是我checkhealth 的
![image](https://github.com/JuanZoran/Trans.nvim/assets/29500263/af505c7a-90eb-47e2-9d35-f788bfc963da)
这是我的Trans.json配置
{
    "dir": "/home/lyy/.local/share/nvim/lazy/Trans.nvim/",
    "theme": "default",
    "strategy": {
        "default": {
            "frontend": "hover",
            "backend": "*"
        }
    },
 .....
}

**Comment by lyy4758** [comment]
字典解压在 .local/share/nvim/lazy/Trans.nvim目录下
![image](https://github.com/JuanZoran/Trans.nvim/assets/29500263/98b9d3e4-40f9-413b-ac7e-d1068d818693)

**Comment by gewuang** [comment]
@lyy4758 遇到相同问题了，请问解决了吗

**Comment by JuanZoran** [comment]
建议检查一下字典是否下载完整了, 截图看一下字典的大小

**Comment by lyy4758** [comment]
解决了, 手动下载然后解压到目录下,我不知道为什么自动下载解压之后的ultimate.db会变成0

**Comment by lyy4758** [comment]
我想问一下@JuanZoran  怎么让这个float窗口是透明的啊

**Comment by gewuang** [comment]
@lyy4758 赞，我可以了，通过链接下载：https://github.com/skywind3000/ECDICT-ultimate/releases/tag/1.0.0

**Comment by JuanZoran** [comment]
> 我想问一下@JuanZoran 怎么让这个float窗口是透明的啊

修改TransWin的color属性

**Comment by lyy4758** [comment]
能看一下你的配置TransWin的配置吗? 我设置color属性会报错,提示没有这个属性,设置bg和fg的话也没有作用@JuanZoran

**Comment by JuanZoran** [comment]
在Trans启动后也就是setup之后再设置高亮组,不然有可能会被覆盖, 设置成透明的方式是将bg设置成NONE, 具体的api应该是vim.api.nvim_set_hl

**Comment by lyy4758** [comment]
config = function(_, opts)
			require("Trans").setup(opts)
			-- vim.api.nvim_set_hl(0, "TransWin", { bg = "#FF0000" })
			local hl_groups = {
				"TransWaitting",
				"TransPhonetic",
				"TransWeb",
                                "TransWin"
                                   ...
			
			}

			for _, group in ipairs(hl_groups) do
				vim.api.nvim_set_hl(0, group, {bg = 'NONE'})
			end
我把所有Trans的高亮组 bg都设置为NONE了, 我用hilight命令查看了 都设置成功了,但是这个背景没变过 其他的都有变化@JuanZoran
